# Generated by Django 4.0.4 on 2022-05-18 15:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_daterecord_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.IntegerField(),
        ),
    ]
